---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 10m0s
  storageNamespace: authentik
  targetNamespace: authentik

  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: AUTHENTIK_SECRET_KEY
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-secrets
      valuesKey: POSTGRES_PASSWORD
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-secrets
      valuesKey: POSTGRES_PASSWORD
      targetPath: postgresql.auth.password
    - kind: Secret
      name: authentik-secrets
      valuesKey: EMAIL_PASSWORD
      targetPath: authentik.email.password

  values:
    authentik:
      image:
        tag: 2025.12.1
      error_reporting:
        enabled: true
      email:
        host: "mail.infomaniak.com"
        port: 587
        username: "contact@loutik.fr"
        use_tls: true
        use_ssl: false
        from: "Authentik <contact@loutik.fr>"

    server:
      ingress:
        ingressClassName: traefik
        enabled: true
        hosts:
          - sso.loutik.fr

    redis:
      enabled: true
      master:
        persistence:
          enabled: false

    postgresql:
      enabled: true
      primary:
        persistence:
          enabled: true
