apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-state-metrics
      version: ">=5.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    service:
      type: NodePort
      nodePort: 31080